# Generated by Django 4.0.3 on 2022-04-21 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bmasuk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('j_ikan', models.CharField(default='', max_length=100)),
                ('k_ikan', models.IntegerField()),
                ('m_kend', models.CharField(max_length=100)),
                ('p_kend', models.CharField(default='', max_length=100)),
                ('t_datang', models.DateField()),
                ('b_gambar', models.BinaryField()),
            ],
        ),
    ]
