# Generated by Django 4.0.5 on 2022-06-29 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pengguna',
        ),
    ]
