# Generated by Django 4.0.3 on 2022-06-10 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pengguna',
        ),
    ]
