# Generated by Django 4.0.3 on 2022-06-23 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jenisikan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jenisikan',
            name='h_ton',
            field=models.CharField(max_length=999999999),
        ),
    ]
